receivers:
  opencensus:

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          metrics_path: '/statsz'
          static_configs:
            - targets: ["host.docker.internal:8081"]

exporters:
  prometheus:
    endpoint: "host.docker.internal:5050"

  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [jaeger]
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
