{
 "title": "TODO Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(todo_app_http_server_response_count{http_status!~\"[5]..\"}[1m])) / sum(rate(todo_app_http_server_response_count[1m])) ) * 100",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(todo_app_http_server_response_count{http_status=~\"[5]..\"}[1m])) / sum(rate(todo_app_http_server_response_count[1m]))) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(todo_app_http_server_request_count[1m]) * 100"
    }
   ]
  },
  {
   "title": "HTTP Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (http_status) (rate(todo_app_http_server_response_count[1m])) * 100"
    }
   ]
  },
  {
   "title": "Total HTTP Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todo_app_http_server_request_count)"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.5, rate(todo_app_http_server_response_latency_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(todo_app_http_server_response_latency_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, rate(todo_app_http_server_response_latency_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, rate(todo_app_http_server_response_latency_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P50 Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(todo_app_http_server_response_bytes_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P90 Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(todo_app_http_server_response_bytes_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P95 Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(todo_app_http_server_response_bytes_bucket[5m]))"
    }
   ]
  },
  {
   "title": "P99 Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(todo_app_http_server_response_bytes_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todo_app_process_cpu_goroutines)"
    }
   ]
  },
  {
   "title": "Go GC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "todo_app_process_num_gc", "legendFormat": "Total GC" },
    {
     "expr": "rate(todo_app_process_num_gc[1m]) * 100",
     "legendFormat": "GC Rate"
    }
   ]
  },
  {
   "title": "Go Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "todo_app_process_heap_idle", "legendFormat": "idle" },
    { "expr": "todo_app_process_heap_inuse", "legendFormat": "inuse" },
    {
     "expr": "todo_app_process_sys_memory_alloc",
     "legendFormat": "Heap memory from OS"
    }
   ]
  },
  {
   "title": "Go Memory Allocation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "todo_app_process_memory_alloc", "legendFormat": "allocation" }
   ]
  },
  {
   "title": "Task",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "todo_app_task_create_count", "legendFormat": "Created" },
    { "expr": "todo_app_task_update_count", "legendFormat": "Updated" },
    { "expr": "todo_app_task_delete_count", "legendFormat": "Deleted" }
   ]
  }
 ]
}